### ISSUE TITLE
test lab implementation

### ISSUE THREAD

**Issue by Demezy** [Demezy/liquid-simulation#13]
- as a core use  implementation of n-body simulation from lab
- test how it behaves with N particles, where N is:
  - 100
  - 200
  - 500
  - 1000
  - 2000
  - 4000
  -  if perform well  continue till significant freezes 
 
criteria: 
- simple statistics 
- relation between N and time for 1 second simulation
- verdict is it performs well or not

**Comment by Poseidondon** [comment]
Same as #9
